# Generated by Django 6.0.5 on 2026-05-25 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость путешествия'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='places_to_visit',
            field=models.TextField(verbose_name='Места для посещения'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='population_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка населенности'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='safety_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка безопасности'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='transport_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка удобства передвижения'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='vegetation_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка растительности'),
        ),
    ]
